// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {advancement} from '../models';
import {main} from '../models';

export function GetFullWorldState():Promise<advancement.FullWorldState>;

export function LoadConfig():Promise<main.AppConfig>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SendTestEvent():Promise<void>;

export function StartWatching():Promise<void>;

export function StopWatching():Promise<void>;
