// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFullWorldState() {
  return window['go']['main']['App']['GetFullWorldState']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendTestEvent() {
  return window['go']['main']['App']['SendTestEvent']();
}

export function StartWatching() {
  return window['go']['main']['App']['StartWatching']();
}

export function StopWatching() {
  return window['go']['main']['App']['StopWatching']();
}
